In [21]:
import pandas as pd

In [22]:
#Loading the dataset
df = pd.read_csv('csic_database.csv')
df.head(100)

,Unnamed: 0,Method,User-Agent,Pragma,Cache-Control,Accept,Accept-encoding,Accept-charset,language,host,cookie,content-type,connection,lenght,content,classification,URL
0,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=1F767F17239C9B670A39E9B10C3825F4,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/index.jsp HTTP/1.1
1,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=81761ACA043B0E6014CA42A4BCD06AB5,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/anadir.j...
2,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=933185092E0B668B90676E0A2B0767AF,application/x-www-form-urlencoded,Connection: close,Content-Length: 68,id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...,0,http://localhost:8080/tienda1/publico/anadir.j...
3,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=8FA18BA82C5336D03D3A8AFA3E68CBB0,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/autentic...
4,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=7104E6C68A6BCF1423DAE990CE49FEE2,application/x-www-form-urlencoded,Connection: close,Content-Length: 63,modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...,0,http://localhost:8080/tienda1/publico/autentic...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=2B2D9809F71DE72801AB9AC8C38D802B,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/miembros/imagene...
96,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=5D14C0093BB3B57A3A044423898E1FEC,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/miembros/imagene...
97,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=D48ED79C9C22F68E6C8F301B653E0F9F,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/miembros/index.j...
98,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=674146AA4D56A7732EA8F81E8EA86133,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/miembros/editar....
99,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=B80085C250298B68EE218590024528C8,application/x-www-form-urlencoded,Connection: close,Content-Length: 276,modo=registro&login=pacon&password=protoalb%E9...,0,http://localhost:8080/tienda1/miembros/editar....

In [25]:
df.shape

(61065, 17)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61065 entries, 0 to 61064
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       61065 non-null  object
 1   Method           61065 non-null  object
 2   User-Agent       61065 non-null  object
 3   Pragma           61065 non-null  object
 4   Cache-Control    61065 non-null  object
 5   Accept           60668 non-null  object
 6   Accept-encoding  61065 non-null  object
 7   Accept-charset   61065 non-null  object
 8   language         61065 non-null  object
 9   host             61065 non-null  object
 10  cookie           61065 non-null  object
 11  content-type     17977 non-null  object
 12  connection       61065 non-null  object
 13  lenght           17977 non-null  object
 14  content          17977 non-null  object
 15  classification   61065 non-null  int64
 16  URL              61065 non-null  object
dtypes: int64(1), object(16)
memory usage: 7.9+ MB

In [27]:
df.isnull().sum()

Unnamed: 0             0
Method                 0
User-Agent             0
Pragma                 0
Cache-Control          0
Accept               397
Accept-encoding        0
Accept-charset         0
language               0
host                   0
cookie                 0
content-type       43088
connection             0
lenght             43088
content            43088
classification         0
URL                    0
dtype: int64

In [28]:
#Checking the Unnamed Column
df["Unnamed: 0"].head()

0    Normal
1    Normal
2    Normal
3    Normal
4    Normal
Name: Unnamed: 0, dtype: object

In [29]:
df["classification"].value_counts()

classification
0    36000
1    25065
Name: count, dtype: int64

In [30]:
df["Unnamed: 0"].value_counts()

Unnamed: 0
Normal       36000
Anomalous    25065
Name: count, dtype: int64

In [31]:
pd.crosstab(df["Unnamed: 0"], df["classification"])

classification      0      1
Unnamed: 0
Anomalous           0  25065
Normal          36000      0

In [32]:
#Both Unnamed and Classification represent the same information so we are going to drop the Unnamed column
df = df.drop(columns=["Unnamed: 0"])
df = df.rename(columns={"classification": "label"})

In [33]:
df.head()

,Method,User-Agent,Pragma,Cache-Control,Accept,Accept-encoding,Accept-charset,language,host,cookie,content-type,connection,lenght,content,label,URL
0,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=1F767F17239C9B670A39E9B10C3825F4,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/index.jsp HTTP/1.1
1,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=81761ACA043B0E6014CA42A4BCD06AB5,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/anadir.j...
2,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=933185092E0B668B90676E0A2B0767AF,application/x-www-form-urlencoded,Connection: close,Content-Length: 68,id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...,0,http://localhost:8080/tienda1/publico/anadir.j...
3,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=8FA18BA82C5336D03D3A8AFA3E68CBB0,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/autentic...
4,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=7104E6C68A6BCF1423DAE990CE49FEE2,application/x-www-form-urlencoded,Connection: close,Content-Length: 63,modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...,0,http://localhost:8080/tienda1/publico/autentic...

In [15]:
df.columns

Index(['Method', 'User-Agent', 'Pragma', 'Cache-Control', 'Accept',
       'Accept-encoding', 'Accept-charset', 'language', 'host', 'cookie',
       'content-type', 'connection', 'lenght', 'content', 'label', 'URL'],
      dtype='object')

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61065 entries, 0 to 61064
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Method           61065 non-null  object
 1   User-Agent       61065 non-null  object
 2   Pragma           61065 non-null  object
 3   Cache-Control    61065 non-null  object
 4   Accept           60668 non-null  object
 5   Accept-encoding  61065 non-null  object
 6   Accept-charset   61065 non-null  object
 7   language         61065 non-null  object
 8   host             61065 non-null  object
 9   cookie           61065 non-null  object
 10  content-type     17977 non-null  object
 11  connection       61065 non-null  object
 12  lenght           17977 non-null  object
 13  content          17977 non-null  object
 14  label            61065 non-null  int64
 15  URL              61065 non-null  object
dtypes: int64(1), object(15)
memory usage: 7.5+ MB

In [35]:
df.isnull().sum()

Method                 0
User-Agent             0
Pragma                 0
Cache-Control          0
Accept               397
Accept-encoding        0
Accept-charset         0
language               0
host                   0
cookie                 0
content-type       43088
connection             0
lenght             43088
content            43088
label                  0
URL                    0
dtype: int64

In [36]:
df['label'].value_counts()

label
0    36000
1    25065
Name: count, dtype: int64

In [1]:
#The acceptt columns has 397 missing values , content_type has 43,088 missing values, length hs 43,088 missing values and content has 43, 088 missing values

In [37]:
#fixing the "Lenght: Column Name (Spelling Error)
df = df.rename(columns={"lenght": "content_length"})

In [39]:
df.head()

,Method,User-Agent,Pragma,Cache-Control,Accept,Accept-encoding,Accept-charset,language,host,cookie,content-type,connection,content_length,content,label,URL
0,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=1F767F17239C9B670A39E9B10C3825F4,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/index.jsp HTTP/1.1
1,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=81761ACA043B0E6014CA42A4BCD06AB5,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/anadir.j...
2,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=933185092E0B668B90676E0A2B0767AF,application/x-www-form-urlencoded,Connection: close,Content-Length: 68,id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...,0,http://localhost:8080/tienda1/publico/anadir.j...
3,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=8FA18BA82C5336D03D3A8AFA3E68CBB0,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/autentic...
4,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=7104E6C68A6BCF1423DAE990CE49FEE2,application/x-www-form-urlencoded,Connection: close,Content-Length: 63,modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...,0,http://localhost:8080/tienda1/publico/autentic...

In [40]:
#HAndling Missing Values
#fix the Accept columns
df["Accept"] = df["Accept"].fillna("unknown")

In [41]:
#fix the content_type 
df["content-type"] = df["content-type"].fillna("none")

In [42]:
#fix the content_length
df["content_length"] = df["content_length"].fillna("0")

In [43]:
df.head(100)

,Method,User-Agent,Pragma,Cache-Control,Accept,Accept-encoding,Accept-charset,language,host,cookie,content-type,connection,content_length,content,label,URL
0,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=1F767F17239C9B670A39E9B10C3825F4,none,close,0,NaN,0,http://localhost:8080/tienda1/index.jsp HTTP/1.1
1,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=81761ACA043B0E6014CA42A4BCD06AB5,none,close,0,NaN,0,http://localhost:8080/tienda1/publico/anadir.j...
2,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=933185092E0B668B90676E0A2B0767AF,application/x-www-form-urlencoded,Connection: close,Content-Length: 68,id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...,0,http://localhost:8080/tienda1/publico/anadir.j...
3,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=8FA18BA82C5336D03D3A8AFA3E68CBB0,none,close,0,NaN,0,http://localhost:8080/tienda1/publico/autentic...
4,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=7104E6C68A6BCF1423DAE990CE49FEE2,application/x-www-form-urlencoded,Connection: close,Content-Length: 63,modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...,0,http://localhost:8080/tienda1/publico/autentic...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=2B2D9809F71DE72801AB9AC8C38D802B,none,close,0,NaN,0,http://localhost:8080/tienda1/miembros/imagene...
96,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=5D14C0093BB3B57A3A044423898E1FEC,none,close,0,NaN,0,http://localhost:8080/tienda1/miembros/imagene...
97,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=D48ED79C9C22F68E6C8F301B653E0F9F,none,close,0,NaN,0,http://localhost:8080/tienda1/miembros/index.j...
98,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=674146AA4D56A7732EA8F81E8EA86133,none,close,0,NaN,0,http://localhost:8080/tienda1/miembros/editar....
99,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=B80085C250298B68EE218590024528C8,application/x-www-form-urlencoded,Connection: close,Content-Length: 276,modo=registro&login=pacon&password=protoalb%E9...,0,http://localhost:8080/tienda1/miembros/editar....

In [44]:
#converting to Numerica values
df["content_length"] = pd.to_numeric(df["content_length"], errors="coerce")
df["content_length"] = df["content_length"].fillna(0)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61065 entries, 0 to 61064
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Method           61065 non-null  object
 1   User-Agent       61065 non-null  object
 2   Pragma           61065 non-null  object
 3   Cache-Control    61065 non-null  object
 4   Accept           61065 non-null  object
 5   Accept-encoding  61065 non-null  object
 6   Accept-charset   61065 non-null  object
 7   language         61065 non-null  object
 8   host             61065 non-null  object
 9   cookie           61065 non-null  object
 10  content-type     61065 non-null  object
 11  connection       61065 non-null  object
 12  content_length   61065 non-null  float64
 13  content          17977 non-null  object
 14  label            61065 non-null  int64
 15  URL              61065 non-null  object
dtypes: float64(1), int64(1), object(14)
memory usage: 7.5+ MB

In [46]:
df["content"] = df["content"].fillna("")

In [49]:
#Normalizing all text columns 
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = df[col].str.lower().str.strip()

In [50]:
#Checking forf Duplicated rows
df.duplicated().sum()

np.int64(0)

In [51]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61065 entries, 0 to 61064
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Method           61065 non-null  object
 1   User-Agent       61065 non-null  object
 2   Pragma           61065 non-null  object
 3   Cache-Control    61065 non-null  object
 4   Accept           61065 non-null  object
 5   Accept-encoding  61065 non-null  object
 6   Accept-charset   61065 non-null  object
 7   language         61065 non-null  object
 8   host             61065 non-null  object
 9   cookie           61065 non-null  object
 10  content-type     61065 non-null  object
 11  connection       61065 non-null  object
 12  content_length   61065 non-null  float64
 13  content          61065 non-null  object
 14  label            61065 non-null  int64
 15  URL              61065 non-null  object
dtypes: float64(1), int64(1), object(14)
memory usage: 7.5+ MB

Method             0
User-Agent         0
Pragma             0
Cache-Control      0
Accept             0
Accept-encoding    0
Accept-charset     0
language           0
host               0
cookie             0
content-type       0
connection         0
content_length     0
content            0
label              0
URL                0
dtype: int64

In [52]:
#Clean datasset, no missing values, no duplicates , all text is normalized , changed classification to label columns

In [53]:
#Saving the Clean version of the dataset
df.to_csv("csic_cleaned.csv", index=False)

In [1]:
#FEATURE ENGINEERING
import pandas as pd
import numpy as np
import re
from urllib.parse import unquote

#Loading the cleaned data
df = pd.read_csv('../data/cleaned/csic_cleaned_final.csv')


print(f"Loaded clean dataset")
print(f"   Shape: {df.shape}")
print(f"   Columns: {df.columns.tolist()}")
print(f"\nLabel distribution:")
print(df['label'].value_counts())

Loaded clean dataset
   Shape: (61065, 10)
   Columns: ['method', 'accept', 'cookie', 'content_type', 'connection', 'content_length', 'body', 'label', 'url_path', 'query_string']

Label distribution:
label
0    36000
1    25065
Name: count, dtype: int64

In [2]:

# GROUP 1 — URL FEATURES (complete)


def calculate_entropy(s):
    """Shannon entropy — measures randomness of a string."""
    if not s or len(s) == 0:
        return 0.0
    probs = [s.count(c) / len(s) for c in set(s)]
    return round(-sum(p * np.log2(p) for p in probs if p > 0), 4)


def extract_url_features(url):
    """Extract numeric features from url_path column."""
    if not isinstance(url, str) or url == '':
        url = ''
    
    return pd.Series({
        'url_length':              len(url),
        'url_path_depth':          url.count('/'),
        'url_num_dots':            url.count('.'),
        'url_num_special':         len(re.findall(r'[<>\'\";\(\)\{\}]', url)),
        'url_num_hyphens':         url.count('-'),
        'url_num_underscores':     url.count('_'),
        'url_num_percent':         url.count('%'),
        'url_num_equal':           url.count('='),
        'url_num_ampersand':       url.count('&'),
        'url_entropy':             calculate_entropy(url),
        'url_has_risky_ext':       int(bool(re.search(
            r'\.(php|asp|aspx|jsp|cgi|exe|sh|bat|cmd|pl|py)$',
            url, re.IGNORECASE
        ))),
        'url_has_double_encoding': int('%25' in url.lower()),
    })


# Fix nulls first
df['url_path']     = df['url_path'].fillna('')
df['query_string'] = df['query_string'].fillna('')
df['body']         = df['body'].fillna('')

# Apply to dataset
print(" Extracting URL features...")
url_features = df['url_path'].apply(extract_url_features)

print(f" URL features extracted: {url_features.shape[1]} features")
print(f"   Shape: {url_features.shape}")
print(f"\nFeature names: {url_features.columns.tolist()}")
print(f"\nSample values (first 3 rows):")
print(url_features.head(3))

# Quick sanity check — compare normal vs anomalous
url_features['label'] = df['label'].values
print(f"\nMean URL length by class:")
print(url_features.groupby('label')['url_length'].mean())
url_features = url_features.drop(columns=['label'])

 Extracting URL features...
 URL features extracted: 12 features
   Shape: (61065, 12)

Feature names: ['url_length', 'url_path_depth', 'url_num_dots', 'url_num_special', 'url_num_hyphens', 'url_num_underscores', 'url_num_percent', 'url_num_equal', 'url_num_ampersand', 'url_entropy', 'url_has_risky_ext', 'url_has_double_encoding']

Sample values (first 3 rows):
   url_length  url_path_depth  url_num_dots  url_num_special  url_num_hyphens  \
0        18.0             2.0           1.0              0.0              0.0
1        96.0             3.0           1.0              0.0              0.0
2        27.0             3.0           1.0              0.0              0.0

   url_num_underscores  url_num_percent  url_num_equal  url_num_ampersand  \
0                  0.0              0.0            0.0                0.0
1                  0.0              1.0            5.0                4.0
2                  0.0              0.0            0.0                0.0

   url_entropy  url_has_risky_ext  url_has_double_encoding
0       3.6144                1.0                      0.0
1       4.6134                0.0                      0.0
2       4.0043                1.0                      0.0

Mean URL length by class:
label
0    48.985944
1    76.575145
Name: url_length, dtype: float64

In [3]:

# GROUP 2 — QUERY STRING FEATURES


# Attack patterns compiled once for efficiency
SQLI_PATTERN = re.compile(
    r"(\'|--|;|\bOR\b|\bAND\b|\bUNION\b|\bSELECT\b|\bDROP\b"
    r"|\bINSERT\b|\bDELETE\b|\bEXEC\b|\bSLEEP\b|\bWAITFOR\b"
    r"|\b1=1\b|\b1=2\b)",
    re.IGNORECASE
)
XSS_PATTERN = re.compile(
    r"(<script|javascript:|onerror=|onload=|alert\(|"
    r"document\.cookie|<iframe|eval\(|<img)",
    re.IGNORECASE
)
TRAVERSAL_PATTERN = re.compile(
    r"(\.\./|\.\.\\|%2e%2e|/etc/passwd|/etc/shadow|cmd\.exe)",
    re.IGNORECASE
)
ENCODING_PATTERN = re.compile(r"(%[0-9a-fA-F]{2})")


def extract_query_features(query):
    """Extract features from query string column."""
    if not isinstance(query, str) or query == '':
        return pd.Series({
            'query_length':        0,
            'query_num_params':    0,
            'query_num_equals':    0,
            'query_num_special':   0,
            'query_num_percent':   0,
            'query_entropy':       0.0,
            'query_has_sqli':      0,
            'query_has_xss':       0,
            'query_has_traversal': 0,
            'query_has_encoding':  0,
            'query_is_empty':      1,
        })

    try:
        query_decoded = unquote(query)
    except Exception:
        query_decoded = query

    return pd.Series({
        'query_length':        len(query),
        'query_num_params':    query.count('&') + 1,
        'query_num_equals':    query.count('='),
        'query_num_special':   len(re.findall(r'[<>\'\";\(\)\{\}]', query_decoded)),
        'query_num_percent':   query.count('%'),
        'query_entropy':       calculate_entropy(query),
        'query_has_sqli':      int(bool(SQLI_PATTERN.search(query_decoded))),
        'query_has_xss':       int(bool(XSS_PATTERN.search(query_decoded))),
        'query_has_traversal': int(bool(TRAVERSAL_PATTERN.search(query_decoded))),
        'query_has_encoding':  int(bool(ENCODING_PATTERN.search(query))),
        'query_is_empty':      0,
    })


# Applying to dataset
print(" Extracting query string features...")
query_features = df['query_string'].apply(extract_query_features)

print(f" Query features extracted: {query_features.shape[1]} features")
print(f"   Shape: {query_features.shape}")
print(f"\nFeature names: {query_features.columns.tolist()}")
print(f"\nSample values (first 3 rows):")
print(query_features.head(3))

#  checking — attack flags
print(f"\nAttack flags detected in query strings:")
print(f"  SQLi:      {query_features['query_has_sqli'].sum():,} requests")
print(f"  XSS:       {query_features['query_has_xss'].sum():,} requests")
print(f"  Traversal: {query_features['query_has_traversal'].sum():,} requests")
print(f"  Encoding:  {query_features['query_has_encoding'].sum():,} requests")
print(f"  Empty:     {query_features['query_is_empty'].sum():,} requests")

# Comparing query length normal vs attack
query_features['label'] = df['label'].values
print(f"\nMean query length by class:")
print(query_features.groupby('label')['query_length'].mean())
query_features = query_features.drop(columns=['label'])

 Extracting query string features...
 Query features extracted: 11 features
   Shape: (61065, 11)

Feature names: ['query_length', 'query_num_params', 'query_num_equals', 'query_num_special', 'query_num_percent', 'query_entropy', 'query_has_sqli', 'query_has_xss', 'query_has_traversal', 'query_has_encoding', 'query_is_empty']

Sample values (first 3 rows):
   query_length  query_num_params  query_num_equals  query_num_special  \
0           0.0               0.0               0.0                0.0
1          68.0               5.0               5.0                0.0
2           0.0               0.0               0.0                0.0

   query_num_percent  query_entropy  query_has_sqli  query_has_xss  \
0                0.0         0.0000             0.0            0.0
1                1.0         4.4256             0.0            0.0
2                0.0         0.0000             0.0            0.0

   query_has_traversal  query_has_encoding  query_is_empty
0                  0.0                 0.0             1.0
1                  0.0                 1.0             0.0
2                  0.0                 0.0             1.0

Attack flags detected in query strings:
  SQLi:      2,185.0 requests
  XSS:       368.0 requests
  Traversal: 97.0 requests
  Encoding:  10,610.0 requests
  Empty:     43,456.0 requests

Mean query length by class:
label
0    20.347056
1    47.133613
Name: query_length, dtype: float64

In [5]:

# GROUP 3 — BODY / PAYLOAD FEATURES


def extract_body_features(body):
    """Extract features from HTTP request body."""
    if not isinstance(body, str) or body == '':
        return pd.Series({
            'body_length':          0,
            'body_entropy':         0.0,
            'body_num_params':      0,
            'body_num_special':     0,
            'body_num_percent':     0,
            'body_num_quotes':      0,
            'body_num_semicolons':  0,
            'body_num_brackets':    0,
            'body_has_sqli':        0,
            'body_has_xss':         0,
            'body_has_traversal':   0,
            'body_has_encoding':    0,
            'body_is_empty':        1,
        })

    try:
        body_decoded = unquote(body)
    except Exception:
        body_decoded = body

    return pd.Series({
        'body_length':         len(body),
        'body_entropy':        calculate_entropy(body),
        'body_num_params':     body.count('&') + 1,
        'body_num_special':    len(re.findall(r'[<>\";\(\)\{\}]', body_decoded)),
        'body_num_percent':    body.count('%'),
        'body_num_quotes':     body.count("'") + body.count('"'),
        'body_num_semicolons': body.count(';'),
        'body_num_brackets':   body.count('(') + body.count(')'),
        'body_has_sqli':       int(bool(SQLI_PATTERN.search(body_decoded))),
        'body_has_xss':        int(bool(XSS_PATTERN.search(body_decoded))),
        'body_has_traversal':  int(bool(TRAVERSAL_PATTERN.search(body_decoded))),
        'body_has_encoding':   int(bool(ENCODING_PATTERN.search(body))),
        'body_is_empty':       0,
    })


# Applying  to dataset
print(" Extracting body/payload features...")
body_features = df['body'].apply(extract_body_features)

print(f" Body features extracted: {body_features.shape[1]} features")
print(f"   Shape: {body_features.shape}")
print(f"\nFeature names: {body_features.columns.tolist()}")
print(f"\nSample values (first 3 rows):")
print(body_features.head(3))

#  checking 
print(f"\nAttack flags detected in body:")
print(f"  SQLi:      {body_features['body_has_sqli'].sum():,} requests")
print(f"  XSS:       {body_features['body_has_xss'].sum():,} requests")
print(f"  Traversal: {body_features['body_has_traversal'].sum():,} requests")
print(f"  Encoding:  {body_features['body_has_encoding'].sum():,} requests")
print(f"  Empty:     {body_features['body_is_empty'].sum():,} requests")

# Comparing body length normal vs attack
body_features['label'] = df['label'].values
print(f"\nMean body length by class:")
print(body_features.groupby('label')['body_length'].mean())
body_features = body_features.drop(columns=['label'])

 Extracting body/payload features...
 Body features extracted: 13 features
   Shape: (61065, 13)

Feature names: ['body_length', 'body_entropy', 'body_num_params', 'body_num_special', 'body_num_percent', 'body_num_quotes', 'body_num_semicolons', 'body_num_brackets', 'body_has_sqli', 'body_has_xss', 'body_has_traversal', 'body_has_encoding', 'body_is_empty']

Sample values (first 3 rows):
   body_length  body_entropy  body_num_params  body_num_special  \
0          0.0        0.0000              0.0               0.0
1          0.0        0.0000              0.0               0.0
2         68.0        4.4256              5.0               0.0

   body_num_percent  body_num_quotes  body_num_semicolons  body_num_brackets  \
0               0.0              0.0                  0.0                0.0
1               0.0              0.0                  0.0                0.0
2               1.0              0.0                  0.0                0.0

   body_has_sqli  body_has_xss  body_has_traversal  body_has_encoding  \
0            0.0           0.0                 0.0                0.0
1            0.0           0.0                 0.0                0.0
2            0.0           0.0                 0.0                1.0

   body_is_empty
0            1.0
1            1.0
2            0.0

Attack flags detected in body:
  SQLi:      2,191.0 requests
  XSS:       368.0 requests
  Traversal: 97.0 requests
  Encoding:  10,785.0 requests
  Empty:     43,088.0 requests

Mean body length by class:
label
0    20.347056
1    48.583004
Name: body_length, dtype: float64

In [6]:

# GROUP 4 — HTTP METHOD FEATURES


def extract_method_features(method):
    """Extract features from HTTP method column."""
    method = str(method).upper().strip() if isinstance(method, str) else 'UNKNOWN'

    return pd.Series({
        'method_get':        int(method == 'GET'),
        'method_post':       int(method == 'POST'),
        'method_put':        int(method == 'PUT'),
        'method_suspicious': int(method in ['DELETE', 'TRACE',
                                            'CONNECT', 'UNKNOWN']),
    })


# Applying to dataset
print(" Extracting method features...")
method_features = df['method'].apply(extract_method_features)

print(f" Method features extracted: {method_features.shape[1]} features")
print(f"   Shape: {method_features.shape}")
print(f"\nFeature names: {method_features.columns.tolist()}")
print(f"\nSample values (first 3 rows):")
print(method_features.head(3))

# Checking 
print(f"\nMethod distribution:")
print(f"  GET:         {method_features['method_get'].sum():,} requests")
print(f"  POST:        {method_features['method_post'].sum():,} requests")
print(f"  PUT:         {method_features['method_put'].sum():,} requests")
print(f"  Suspicious:  {method_features['method_suspicious'].sum():,} requests")

# Comparing  methods across classes
method_features['label'] = df['label'].values
print(f"\nMethod distribution by class:")
print(method_features.groupby('label')[
    ['method_get','method_post','method_put','method_suspicious']
].sum())
method_features = method_features.drop(columns=['label'])

 Extracting method features...
 Method features extracted: 4 features
   Shape: (61065, 4)

Feature names: ['method_get', 'method_post', 'method_put', 'method_suspicious']

Sample values (first 3 rows):
   method_get  method_post  method_put  method_suspicious
0           1            0           0                  0
1           1            0           0                  0
2           0            1           0                  0

Method distribution:
  GET:         43,088 requests
  POST:        17,580 requests
  PUT:         397 requests
  Suspicious:  0 requests

Method distribution by class:
       method_get  method_post  method_put  method_suspicious
label
0           28000         8000           0                  0
1           15088         9580         397                  0

In [7]:

# GROUP 5 — HEADER FEATURES


def extract_header_features(row):
    """Extract features from header columns."""

    cookie       = str(row['cookie'])       if pd.notna(row['cookie'])       else ''
    content_type = str(row['content_type']) if pd.notna(row['content_type']) else ''
    connection   = str(row['connection'])   if pd.notna(row['connection'])   else ''
    accept       = str(row['accept'])       if pd.notna(row['accept'])       else ''
    method       = str(row['method'])       if pd.notna(row['method'])       else ''
    body         = str(row['body'])         if pd.notna(row['body'])         else ''
    content_len  = int(row['content_length']) if pd.notna(row['content_length']) else 0

    return pd.Series({
        # Cookie features
        'cookie_length':          len(cookie),
        'cookie_has_sqli':        int(bool(SQLI_PATTERN.search(cookie))),
        'cookie_has_xss':         int(bool(XSS_PATTERN.search(cookie))),
        'cookie_is_present':      int(cookie not in ['', 'none', 'MISSING']),

        # Content type features
        'content_type_is_form':   int('form' in content_type.lower()),
        'content_type_is_json':   int('json' in content_type.lower()),
        'content_type_is_none':   int(content_type in ['none', '', 'MISSING']),

        # Connection features
        'connection_is_close':    int('close' in connection.lower()),
        'connection_keep_alive':  int('keep-alive' in connection.lower()),

        # Request consistency checks
        # POST without content type = suspicious
        'post_no_content_type':   int(
            method == 'POST' and
            content_type in ['none', '', 'MISSING']
        ),
        # GET with body = suspicious
        'get_with_body':          int(
            method == 'GET' and
            len(body.strip()) > 0
        ),
        # POST with empty body = suspicious
        'post_empty_body':        int(
            method == 'POST' and
            len(body.strip()) == 0
        ),
        # Content length mismatch
        'content_length_mismatch': int(
            content_len == 0 and
            len(body.strip()) > 0
        ),
    })


# Apply to dataset
print(" Extracting header features...")
header_features = df.apply(extract_header_features, axis=1)

print(f" Header features extracted: {header_features.shape[1]} features")
print(f"   Shape: {header_features.shape}")
print(f"\nFeature names: {header_features.columns.tolist()}")
print(f"\nSample values (first 3 rows):")
print(header_features.head(3))

# Checking 
print(f"\nRequest consistency anomalies:")
print(f"  POST no content-type:     {header_features['post_no_content_type'].sum():,}")
print(f"  GET with body:            {header_features['get_with_body'].sum():,}")
print(f"  POST empty body:          {header_features['post_empty_body'].sum():,}")
print(f"  Content length mismatch:  {header_features['content_length_mismatch'].sum():,}")
print(f"  Cookie has SQLi:          {header_features['cookie_has_sqli'].sum():,}")
print(f"  Cookie has XSS:           {header_features['cookie_has_xss'].sum():,}")

 Extracting header features...
 Header features extracted: 13 features
   Shape: (61065, 13)

Feature names: ['cookie_length', 'cookie_has_sqli', 'cookie_has_xss', 'cookie_is_present', 'content_type_is_form', 'content_type_is_json', 'content_type_is_none', 'connection_is_close', 'connection_keep_alive', 'post_no_content_type', 'get_with_body', 'post_empty_body', 'content_length_mismatch']

Sample values (first 3 rows):
   cookie_length  cookie_has_sqli  cookie_has_xss  cookie_is_present  \
0             43                0               0                  1
1             43                0               0                  1
2             43                0               0                  1

   content_type_is_form  content_type_is_json  content_type_is_none  \
0                     0                     0                     1
1                     0                     0                     1
2                     1                     0                     0

   connection_is_close  connection_keep_alive  post_no_content_type  \
0                    1                      0                     0
1                    1                      0                     0
2                    1                      0                     0

   get_with_body  post_empty_body  content_length_mismatch
0              0                0                        0
1              0                0                        0
2              0                0                        0

Request consistency anomalies:
  POST no content-type:     0
  GET with body:            0
  POST empty body:          0
  Content length mismatch:  0
  Cookie has SQLi:          0
  Cookie has XSS:           0

In [8]:

# COMBINE ALL FEATURE GROUPS


print(" Combining all feature groups...")

# Combining all groups horizontally
feature_matrix = pd.concat([
    url_features,
    query_features,
    body_features,
    method_features,
    header_features,
], axis=1)

# Adding  label column
feature_matrix['label'] = df['label'].values

print(f" Feature matrix created")
print(f"   Shape: {feature_matrix.shape}")
print(f"   Total features: {feature_matrix.shape[1] - 1}")
print(f"\nAll feature names:")
for i, col in enumerate(feature_matrix.columns[:-1], 1):
    print(f"  {i:2}. {col}")

# Checking  for any null values  in final matrix
nulls = feature_matrix.isnull().sum().sum()
print(f"\nTotal nulls in feature matrix: {nulls}")

# Label distribution checking 
print(f"\nLabel distribution:")
print(feature_matrix['label'].value_counts())

# Preview
print(f"\nFirst 3 rows:")
feature_matrix.head(3)

 Combining all feature groups...
 Feature matrix created
   Shape: (61065, 54)
   Total features: 53

All feature names:
   1. url_length
   2. url_path_depth
   3. url_num_dots
   4. url_num_special
   5. url_num_hyphens
   6. url_num_underscores
   7. url_num_percent
   8. url_num_equal
   9. url_num_ampersand
  10. url_entropy
  11. url_has_risky_ext
  12. url_has_double_encoding
  13. query_length
  14. query_num_params
  15. query_num_equals
  16. query_num_special
  17. query_num_percent
  18. query_entropy
  19. query_has_sqli
  20. query_has_xss
  21. query_has_traversal
  22. query_has_encoding
  23. query_is_empty
  24. body_length
  25. body_entropy
  26. body_num_params
  27. body_num_special
  28. body_num_percent
  29. body_num_quotes
  30. body_num_semicolons
  31. body_num_brackets
  32. body_has_sqli
  33. body_has_xss
  34. body_has_traversal
  35. body_has_encoding
  36. body_is_empty
  37. method_get
  38. method_post
  39. method_put
  40. method_suspicious
  41. cookie_length
  42. cookie_has_sqli
  43. cookie_has_xss
  44. cookie_is_present
  45. content_type_is_form
  46. content_type_is_json
  47. content_type_is_none
  48. connection_is_close
  49. connection_keep_alive
  50. post_no_content_type
  51. get_with_body
  52. post_empty_body
  53. content_length_mismatch

Total nulls in feature matrix: 0

Label distribution:
label
0    36000
1    25065
Name: count, dtype: int64

First 3 rows:

,url_length,url_path_depth,url_num_dots,url_num_special,url_num_hyphens,url_num_underscores,url_num_percent,url_num_equal,url_num_ampersand,url_entropy,...,content_type_is_form,content_type_is_json,content_type_is_none,connection_is_close,connection_keep_alive,post_no_content_type,get_with_body,post_empty_body,content_length_mismatch,label
0,18.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3.6144,...,0,0,1,1,0,0,0,0,0,0
1,96.0,3.0,1.0,0.0,0.0,0.0,1.0,5.0,4.0,4.6134,...,0,0,1,1,0,0,0,0,0,0
2,27.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0043,...,1,0,0,1,0,0,0,0,0,0

In [9]:
#SAVING AND SPLITTING INTO TRAIN/TEST SPLIT 

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import joblib

# SAVE + TRAIN/TEST SPLIT


#  Save full feature matrix
feature_matrix.to_csv('../data/features/feature_matrix.csv', index=False)
print(f" Saved full feature matrix → data/features/feature_matrix.csv")
print(f"   Shape: {feature_matrix.shape}")

#  Separating  features and label 
X = feature_matrix.drop(columns=['label'])
y = feature_matrix['label']

print(f"\n Features (X): {X.shape}")
print(f"   Label (y):    {y.shape}")

#  Train/Test Split (80/20 stratified) 
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y        
)

print(f"\n Train/Test Split:")
print(f"   X_train: {X_train.shape}")
print(f"   X_test:  {X_test.shape}")
print(f"   y_train distribution: {y_train.value_counts().to_dict()}")
print(f"   y_test distribution:  {y_test.value_counts().to_dict()}")

#  Scaling features 
# Fit ONLY on training data — never on test data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

print(f"\n Features scaled using StandardScaler")
print(f"   Fitted on training data only")

#  Save train/test splits 
train_df = pd.DataFrame(X_train_scaled, columns=X.columns)
train_df['label'] = y_train.values
train_df.to_csv('../data/final/train.csv', index=False)

test_df = pd.DataFrame(X_test_scaled, columns=X.columns)
test_df['label'] = y_test.values
test_df.to_csv('../data/final/test.csv', index=False)

print(f"\nSaved train set → data/final/train.csv")
print(f"   Shape: {train_df.shape}")
print(f"\nSaved test set  → data/final/test.csv")
print(f"   Shape: {test_df.shape}")

#  Save scaler for team 
joblib.dump(scaler, '../data/final/scaler.pkl')
print(f"\n Saved scaler → data/final/scaler.pkl")

#  Save feature names 
with open('../data/final/feature_names.txt', 'w') as f:
    f.write('\n'.join(X.columns.tolist()))
print(f" Saved feature names → data/final/feature_names.txt")

#  Final summary 
print(f"""
{'='*50}
FEATURE ENGINEERING COMPLETE
{'='*50}
Total features:     {X.shape[1]}
Training samples:   {X_train.shape[0]:,}
Testing samples:    {X_test.shape[0]:,}
Total samples:      {len(X):,}

Files saved to data/final/:
   train.csv
   test.csv
   scaler.pkl
   feature_names.txt
{'='*50}
""")

 Saved full feature matrix → data/features/feature_matrix.csv
   Shape: (61065, 54)

 Features (X): (61065, 53)
   Label (y):    (61065,)

 Train/Test Split:
   X_train: (48852, 53)
   X_test:  (12213, 53)
   y_train distribution: {0: 28800, 1: 20052}
   y_test distribution:  {0: 7200, 1: 5013}

 Features scaled using StandardScaler
   Fitted on training data only

Saved train set → data/final/train.csv
   Shape: (48852, 54)

Saved test set  → data/final/test.csv
   Shape: (12213, 54)

 Saved scaler → data/final/scaler.pkl
 Saved feature names → data/final/feature_names.txt

==================================================
FEATURE ENGINEERING COMPLETE
==================================================
Total features:     53
Training samples:   48,852
Testing samples:    12,213
Total samples:      61,065

Files saved to data/final/:
   train.csv
   test.csv
   scaler.pkl
   feature_names.txt
==================================================